# Site settings
title:              "vando's blog"
author:             Facundo Bianco
description:        "Another geek blog and related stuff"
url:                "http://van.do"
baseurl:            ""

# Google analytics
google_analytics:   "UA-60019948-1"

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:   vandosblog

# Social icons
show_social_icons:  true
github_username:    vando
twitter_username:   vando

# tags
tags:               ['cli', 'script', 'net', 'x11']

# Build settings
markdown:           redcarpet
redcarpet:
  extensions:       ['smart', 'tables', 'with_toc_data', 'footnotes', 'autolink']
permalink:          /:title/
paginate:           7
paginate_path:      /page:num/
sass:
  compressed:       true
